<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Ardel.Bootstrapper</RootNamespace>
    <AssemblyName>Ardel</AssemblyName>
    <ApplicationIcon>..\Ardel.Launcher\Assets\app.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <Product>Ardel</Product>
    <Title>Ardel</Title>
    <AssemblyTitle>Ardel Desktop Client</AssemblyTitle>
    <Description>Ardel Desktop Client</Description>
    <Company>Ice Tea Studio</Company>
    <Authors>Ice Tea Studio</Authors>
    <Copyright>Copyright (c) 2026 Ice Tea Studio. All rights reserved.</Copyright>
    <Version>1.5.3</Version>
    <AssemblyVersion>1.5.3.0</AssemblyVersion>
    <FileVersion>1.5.3.0</FileVersion>
    <PackageLicenseExpression>OSL-3.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/FlameGemini/Ardel</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
  </ItemGroup>
</Project>
