// <auto-generated> by tools/crash-gen/emit_rules_only.py
namespace Ardel.Launcher.Services.CrashAnalysis;

internal static class CrashRuleCatalog
{
    public static readonly CrashRuleDefinition[] Rules =
    [
        new CrashRuleDefinition
        {
            Id = "R001",
            Cause = "ManualDebugCrash",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsPreferCrashReport(facts, "Manually triggered debug crash", "Someone is holding F3 + C for 10 seconds")
        },
        new CrashRuleDefinition
        {
            Id = "R003",
            Cause = "X86JavaMemoryLimit",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Could not reserve enough space for object heap", "1048576KB")
        },
        new CrashRuleDefinition
        {
            Id = "R041",
            Cause = "OutOfMemoryMetaspace",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OutOfMemoryError: Metaspace", "Out of memory: Metaspace")
        },
        new CrashRuleDefinition
        {
            Id = "R042",
            Cause = "OutOfMemoryGCOverhead",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OutOfMemoryError: GC overhead limit exceeded")
        },
        new CrashRuleDefinition
        {
            Id = "R043",
            Cause = "OutOfMemoryDirectBuffer",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OutOfMemoryError: Direct buffer memory")
        },
        new CrashRuleDefinition
        {
            Id = "R071",
            Cause = "OutOfMemoryArraySize",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OutOfMemoryError: Requested array size exceeds VM limit")
        },
        new CrashRuleDefinition
        {
            Id = "R002",
            Cause = "OutOfMemory",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.OutOfMemoryError", "There is insufficient memory for the Java Runtime Environment")
        },
        new CrashRuleDefinition
        {
            Id = "R004",
            Cause = "JavaTooNew",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.ClassCastException: class jdk.", "module java.base does not export")
        },
        new CrashRuleDefinition
        {
            Id = "R075",
            Cause = "UnsupportedClassVersionDetail",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "compiled by a more recent version of the Java Runtime (class file version")
        },
        new CrashRuleDefinition
        {
            Id = "R005",
            Cause = "JavaIncompatible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "UnsupportedClassVersionError", "Unsupported major.minor version", "has been compiled by a more recent version of the Java Runtime")
        },
        new CrashRuleDefinition
        {
            Id = "R006",
            Cause = "UsingJdk",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "ClassCastException: class java.base/jdk")
        },
        new CrashRuleDefinition
        {
            Id = "R007",
            Cause = "UsingOpenJ9",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OpenJ9 is not supported")
        },
        new CrashRuleDefinition
        {
            Id = "R008",
            Cause = "ModRequiresJava11",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "class file major version 55")
        },
        new CrashRuleDefinition
        {
            Id = "R009",
            Cause = "UnsupportedOpenGl",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "driver does not appear to support OpenGL")
        },
        new CrashRuleDefinition
        {
            Id = "R010",
            Cause = "PixelFormatNotSupported",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Couldn't set pixel format", "Pixel format not accelerated")
        },
        new CrashRuleDefinition
        {
            Id = "R011",
            Cause = "OpenGl1282",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "1282: Invalid operation", "GL_INVALID_OPERATION")
        },
        new CrashRuleDefinition
        {
            Id = "R012",
            Cause = "IntelDriverAccessViolation",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "EXCEPTION_ACCESS_VIOLATION", "# C [ig")
        },
        new CrashRuleDefinition
        {
            Id = "R013",
            Cause = "AmdDriverAccessViolation",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "EXCEPTION_ACCESS_VIOLATION", "# C [atio")
        },
        new CrashRuleDefinition
        {
            Id = "R014",
            Cause = "NvidiaDriverAccessViolation",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "EXCEPTION_ACCESS_VIOLATION", "# C [nvoglv")
        },
        new CrashRuleDefinition
        {
            Id = "R015",
            Cause = "ExtractedModFile",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "extracted jar files", "Extracted mod jars found")
        },
        new CrashRuleDefinition
        {
            Id = "R016",
            Cause = "MissingMixinBootstrap",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "MixinTweaker", "ClassNotFoundException")
        },
        new CrashRuleDefinition
        {
            Id = "R017",
            Cause = "InvalidModFileName",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Invalid module name: empty identifier")
        },
        new CrashRuleDefinition
        {
            Id = "R018",
            Cause = "ShadersModWithOptiFine",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Shaders Mod detected", "OptiFine has built-in shader support")
        },
        new CrashRuleDefinition
        {
            Id = "R019",
            Cause = "OptiFineForgeIncompatible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "OptiFine mods not found")
        },
        new CrashRuleDefinition
        {
            Id = "R020",
            Cause = "OptiFineWorldLoadCrash",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "shouldForceChunkLoad", "OptiFine")
        },
        new CrashRuleDefinition
        {
            Id = "R021",
            Cause = "OldForgeNewJavaIncompatible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "ManifestEntryVerifier", "JarVerifier$VerifierStream")
        },
        new CrashRuleDefinition
        {
            Id = "R022",
            Cause = "IncompleteForgeInstallation",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Missing or invalid fmlcore")
        },
        new CrashRuleDefinition
        {
            Id = "R023",
            Cause = "MultipleForgeInInstanceJson",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "multiple arguments with name fml.forgeVersion")
        },
        new CrashRuleDefinition
        {
            Id = "R024",
            Cause = "NightConfigBug",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "com.electronwill.nightconfig", "ParsingException: Not enough data available")
        },
        new CrashRuleDefinition
        {
            Id = "R025",
            Cause = "ResourcePackTooLarge",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "try a lower resolution resourcepack", "lower resolution resource pack")
        },
        new CrashRuleDefinition
        {
            Id = "R026",
            Cause = "TooManyModsIdLimit",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "maximum id range exceeded", "Maximum id range exceeded")
        },
        new CrashRuleDefinition
        {
            Id = "R027",
            Cause = "FileOrContentValidationFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "signer information does not match")
        },
        new CrashRuleDefinition
        {
            Id = "R028",
            Cause = "DuplicateMods",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "DuplicateModsFoundException", "Found duplicate mod", "Duplicate mods found")
        },
        new CrashRuleDefinition
        {
            Id = "R029",
            Cause = "IncompatibleMods",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Incompatible mods found!")
        },
        new CrashRuleDefinition
        {
            Id = "R030",
            Cause = "MissingDependencyOrWrongMcVersion",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Missing or unsupported mandatory dependencies", "Mod Resolution Exception")
        },
        new CrashRuleDefinition
        {
            Id = "R031",
            Cause = "ConfirmedModCrash",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.NamedModEvidence(facts, "Caught exception from", "LoaderExceptionModCrash")
        },
        new CrashRuleDefinition
        {
            Id = "R032",
            Cause = "ModConfigCrash",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Failed loading config file", "for modid")
        },
        new CrashRuleDefinition
        {
            Id = "R033",
            Cause = "ModMixinFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.NamedModEvidence(facts, "Mixin apply for mod", "mixin.injection.throwable")
        },
        new CrashRuleDefinition
        {
            Id = "R034",
            Cause = "FabricSolutionProvided",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "A potential solution has been determined")
        },
        new CrashRuleDefinition
        {
            Id = "R035",
            Cause = "ForgeError",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "error screen and halt the game")
        },
        new CrashRuleDefinition
        {
            Id = "R036",
            Cause = "ModLoaderError",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Mod resolution failed", "Failure message:")
        },
        new CrashRuleDefinition
        {
            Id = "R037",
            Cause = "ModInitializationFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to create mod instance")
        },
        new CrashRuleDefinition
        {
            Id = "R038",
            Cause = "SpecificBlockCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Block location: World:", "Block: Block{")
        },
        new CrashRuleDefinition
        {
            Id = "R039",
            Cause = "SpecificEntityCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Entity's Exact location", "Entity Type:")
        },
        new CrashRuleDefinition
        {
            Id = "R044",
            Cause = "MissingNativeLibrary",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "UnsatisfiedLinkError", "Unable to load library")
        },
        new CrashRuleDefinition
        {
            Id = "R045",
            Cause = "GlfwWindowFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to create the GLFW window")
        },
        new CrashRuleDefinition
        {
            Id = "R046",
            Cause = "LwjglInitFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load library lwjgl")
        },
        new CrashRuleDefinition
        {
            Id = "R047",
            Cause = "FabricApiMissing",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Fabric API is not installed", "requires fabric-api")
        },
        new CrashRuleDefinition
        {
            Id = "R050",
            Cause = "SodiumIncompatible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "incompatible with Sodium", "requires Sodium", "Indium required")
        },
        new CrashRuleDefinition
        {
            Id = "R051",
            Cause = "IrisShaderIncompatible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Iris requires Sodium", "incompatible with Iris")
        },
        new CrashRuleDefinition
        {
            Id = "R052",
            Cause = "WorldVersionTooNew",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "We need to use the DataFixer", "world was last loaded in version")
        },
        new CrashRuleDefinition
        {
            Id = "R053",
            Cause = "WorldSaveCorrupted",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "Failed to load level", "The save data appears to be corrupt")
        },
        new CrashRuleDefinition
        {
            Id = "R054",
            Cause = "DiskOutOfSpace",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "No space left on device")
        },
        new CrashRuleDefinition
        {
            Id = "R056",
            Cause = "PathTooLong",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "path too long", "Filename longer than", "The filename or extension is too long")
        },
        new CrashRuleDefinition
        {
            Id = "R057",
            Cause = "InvalidOrCorruptJar",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "zip END header not found", "invalid CEN header", "Error reading zip file")
        },
        new CrashRuleDefinition
        {
            Id = "R058",
            Cause = "ModMetadataInvalid",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Could not read fabric.mod.json", "Invalid mods.toml")
        },
        new CrashRuleDefinition
        {
            Id = "R059",
            Cause = "UnrecognizedJvmOption",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Unrecognized option:", "Could not create the Java Virtual Machine")
        },
        new CrashRuleDefinition
        {
            Id = "R060",
            Cause = "BootstrapFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "BootstrapException", "Failed to bootstrap")
        },
        new CrashRuleDefinition
        {
            Id = "R061",
            Cause = "MixinTargetNotFound",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Critical injection failure")
        },
        new CrashRuleDefinition
        {
            Id = "R062",
            Cause = "RenderingBlockCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Block being rendered", "-- Block being rendered")
        },
        new CrashRuleDefinition
        {
            Id = "R063",
            Cause = "RenderingEntityCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "-- Entity being rendered")
        },
        new CrashRuleDefinition
        {
            Id = "R064",
            Cause = "TickingBlockEntityCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "-- Block entity being ticked")
        },
        new CrashRuleDefinition
        {
            Id = "R065",
            Cause = "TickingEntityCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "-- Entity being ticked")
        },
        new CrashRuleDefinition
        {
            Id = "R066",
            Cause = "ServerWatchdog",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "A single server tick took", "ServerHangWatchdog")
        },
        new CrashRuleDefinition
        {
            Id = "R067",
            Cause = "MixinApplyConfigFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Error loading Mixin config", "failed loading mixin config")
        },
        new CrashRuleDefinition
        {
            Id = "R068",
            Cause = "LibraryVersionConflict",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.NoSuchMethodError", "java.lang.AbstractMethodError", "java.lang.IncompatibleClassChangeError")
        },
        new CrashRuleDefinition
        {
            Id = "R069",
            Cause = "OptiFabricConflict",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "OptiFabric", "incompatible")
        },
        new CrashRuleDefinition
        {
            Id = "R070",
            Cause = "LaunchTargetMissing",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Cannot find launch target")
        },
        new CrashRuleDefinition
        {
            Id = "R072",
            Cause = "StackOverflowError",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.StackOverflowError")
        },
        new CrashRuleDefinition
        {
            Id = "R073",
            Cause = "LinkageError",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.LinkageError")
        },
        new CrashRuleDefinition
        {
            Id = "R074",
            Cause = "VerifyError",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "java.lang.VerifyError")
        },
        new CrashRuleDefinition
        {
            Id = "R076",
            Cause = "JdkInternalInaccessible",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "InaccessibleObjectException", "cannot access class")
        },
        new CrashRuleDefinition
        {
            Id = "R077",
            Cause = "IllegalMixin",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Unable to locate mixin")
        },
        new CrashRuleDefinition
        {
            Id = "R078",
            Cause = "FabricLanguageAdapterFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "EntrypointException")
        },
        new CrashRuleDefinition
        {
            Id = "R079",
            Cause = "EntrypointCrash",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Exception in entrypoint")
        },
        new CrashRuleDefinition
        {
            Id = "R080",
            Cause = "MixinConnectorFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Error initializing MixinConnector", "MixinConnector failed")
        },
        new CrashRuleDefinition
        {
            Id = "R081",
            Cause = "ForgeConfigLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "ConfigFileTypeHandler")
        },
        new CrashRuleDefinition
        {
            Id = "R082",
            Cause = "NightConfigPathInvalid",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "InvalidPathException", "nightconfig")
        },
        new CrashRuleDefinition
        {
            Id = "R083",
            Cause = "TomlParseError",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "TomlSyntaxException")
        },
        new CrashRuleDefinition
        {
            Id = "R084",
            Cause = "JsonParseCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "com.google.gson.JsonParseException", "com.google.gson.stream.MalformedJsonException")
        },
        new CrashRuleDefinition
        {
            Id = "R085",
            Cause = "DataPackLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load data pack", "Could not load datapack")
        },
        new CrashRuleDefinition
        {
            Id = "R086",
            Cause = "ResourcePackLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load resource pack")
        },
        new CrashRuleDefinition
        {
            Id = "R087",
            Cause = "ShaderCompileFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Error compiling shader", "Failed to compile shader")
        },
        new CrashRuleDefinition
        {
            Id = "R088",
            Cause = "FramebufferFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Couldn't create framebuffer", "framebuffer incomplete")
        },
        new CrashRuleDefinition
        {
            Id = "R089",
            Cause = "OpenGlContextLost",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "GL_CONTEXT_LOST", "OpenGL context was lost")
        },
        new CrashRuleDefinition
        {
            Id = "R090",
            Cause = "DisplayModeFailed",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Couldn't set fullscreen", "Failed to set display mode")
        },
        new CrashRuleDefinition
        {
            Id = "R091",
            Cause = "AudioEngineFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to start SoundEngine", "OpenAL Error")
        },
        new CrashRuleDefinition
        {
            Id = "R092",
            Cause = "JavaMissingMainClass",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Could not find or load main class", "Error: Could not find or load main class")
        },
        new CrashRuleDefinition
        {
            Id = "R093",
            Cause = "AssetsIndexMissing",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Couldn't load assets index")
        },
        new CrashRuleDefinition
        {
            Id = "R094",
            Cause = "LibraryDownloadCorrupt",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Checksum mismatch", "sha1 does not match")
        },
        new CrashRuleDefinition
        {
            Id = "R095",
            Cause = "VersionJsonInvalid",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to parse version")
        },
        new CrashRuleDefinition
        {
            Id = "R096",
            Cause = "ConcurrentModMutation",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.NamedModEvidence(facts, "ConcurrentModificationException")
        },
        new CrashRuleDefinition
        {
            Id = "R097",
            Cause = "NullDerefNamedMod",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.NamedModEvidence(facts, "NullPointerException")
        },
        new CrashRuleDefinition
        {
            Id = "R098",
            Cause = "AsmTransformFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Transformer failed", "ASM class writer")
        },
        new CrashRuleDefinition
        {
            Id = "R099",
            Cause = "CoreModFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Loading failed for coremod", "coremod failed")
        },
        new CrashRuleDefinition
        {
            Id = "R104",
            Cause = "RegistryDuplicate",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Duplicate registry id")
        },
        new CrashRuleDefinition
        {
            Id = "R105",
            Cause = "TagLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load tags")
        },
        new CrashRuleDefinition
        {
            Id = "R106",
            Cause = "RecipeLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to parse recipe")
        },
        new CrashRuleDefinition
        {
            Id = "R107",
            Cause = "StructureLoadFailed",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load structure", "Unable to load structure")
        },
        new CrashRuleDefinition
        {
            Id = "R108",
            Cause = "ChunkLoadCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Exception loading chunk", "Chunk file at")
        },
        new CrashRuleDefinition
        {
            Id = "R109",
            Cause = "PlayerDataCorrupt",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Failed to load player data")
        },
        new CrashRuleDefinition
        {
            Id = "R110",
            Cause = "LevelStemInvalid",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Invalid level_stem", "Failed to parse level_stem")
        },
        new CrashRuleDefinition
        {
            Id = "R111",
            Cause = "TickingWorldCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Exception ticking world")
        },
        new CrashRuleDefinition
        {
            Id = "R112",
            Cause = "ChunkGenerateCrash",
            Phase = CrashPhase.Primary,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Exception generating new chunk")
        },
        new CrashRuleDefinition
        {
            Id = "R113",
            Cause = "JniCrashSecondary",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts =>
            {
                var text = (facts.HasCrashReport ? facts.CrashReport : string.Empty) +
                           "\n" +
                           (facts.HasHsErr ? facts.HsErr : string.Empty);
                if (!text.Contains("EXCEPTION_ACCESS_VIOLATION", StringComparison.OrdinalIgnoreCase))
                    return null;
                if (text.Contains("# C [ig", StringComparison.OrdinalIgnoreCase) ||
                    text.Contains("# C [atio", StringComparison.OrdinalIgnoreCase) ||
                    text.Contains("# C [nvoglv", StringComparison.OrdinalIgnoreCase))
                    return null;
                return text.Contains("# C [", StringComparison.OrdinalIgnoreCase)
                    ? "EXCEPTION_ACCESS_VIOLATION"
                    : null;
            }
        },
        new CrashRuleDefinition
        {
            Id = "R114",
            Cause = "SafepointTimeout",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Timeout waiting for", "safepoint")
        },
        new CrashRuleDefinition
        {
            Id = "R115",
            Cause = "OutOfMemoryKillByOs",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Out of memory: Kill process", "os::commit_memory failed")
        },
        new CrashRuleDefinition
        {
            Id = "R116",
            Cause = "UnicodePathIssue",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "path contains invalid")
        },
        new CrashRuleDefinition
        {
            Id = "R117",
            Cause = "OneDriveLock",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.ContainsAll(facts, "OneDrive", "Access is denied")
        },
        new CrashRuleDefinition
        {
            Id = "R118",
            Cause = "CurseForgeExtractorResidue",
            Phase = CrashPhase.Fatal,
            Stop = true,
            Match = facts => CrashRuleMatchers.Contains(facts, "Do not extract", "incomplete modpack")
        },
    ];
}
