// <auto-generated> by tools/crash-gen/generate_crash_catalog.py
namespace Ardel.Launcher.Services.CrashAnalysis;

internal static class CrashUsrCatalog
{
    public static readonly UsrRuleDefinition[] Rules =
    [
        new UsrRuleDefinition
        {
            Id = "USR001",
            Kind = "usr_crash_report_suspected_mods",
            Match = facts =>
            {
                if (facts.SuspectedModsFromReport.Count == 0)
                    return null;
                return new CrashMatch
                {
                    RuleId = "USR001",
                    Cause = "UsrSuspectedMods",
                    Phase = CrashPhase.Primary,
                    Evidence = "Suspected Mods: " + string.Join(", ", facts.SuspectedModsFromReport),
                    Mods = facts.SuspectedModsFromReport.Take(5).ToList()
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR002",
            Kind = "usr_stack_mod_names",
            Match = facts =>
            {
                if (facts.StackMappedMods.Count is < 1 or > 5)
                    return null;
                return new CrashMatch
                {
                    RuleId = "USR002",
                    Cause = "UsrStackModNames",
                    Phase = CrashPhase.Primary,
                    Evidence = string.Join(", ", facts.StackMappedMods),
                    Mods = facts.StackMappedMods.ToList()
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR003",
            Kind = "usr_stack_keywords",
            Match = facts =>
            {
                if (facts.StackMappedMods.Count > 0)
                    return null;
                if (facts.StackKeywords.Count is < 1 or > 8)
                    return null;
                return new CrashMatch
                {
                    RuleId = "USR003",
                    Cause = "UsrStackKeywords",
                    Phase = CrashPhase.Primary,
                    Evidence = string.Join(", ", facts.StackKeywords),
                    Keywords = facts.StackKeywords.ToList()
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR004",
            Kind = "usr_mixin_unresolved",
            Match = facts =>
            {
                var mixin = facts.EffectiveMatchText.Contains("mixin", System.StringComparison.OrdinalIgnoreCase)
                            && (facts.EffectiveMatchText.Contains("failed", System.StringComparison.OrdinalIgnoreCase)
                                || facts.EffectiveMatchText.Contains("Critical injection", System.StringComparison.OrdinalIgnoreCase));
                if (!mixin)
                    return null;
                if (facts.SuspectedModsFromReport.Count > 0)
                    return null; // named path belongs to R/USR001
                var keys = facts.StackKeywords.Take(8).ToList();
                if (keys.Count == 0)
                    keys.Add("mixin");
                return new CrashMatch
                {
                    RuleId = "USR004",
                    Cause = "UsrMixinUnresolved",
                    Phase = CrashPhase.Primary,
                    Evidence = CrashEvidenceCollector.FindEvidenceLine(facts, "mixin") ?? "mixin",
                    Keywords = keys
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR005",
            Kind = "usr_npe_unbound",
            Match = facts =>
            {
                if (!facts.EffectiveMatchText.Contains("NullPointerException", System.StringComparison.OrdinalIgnoreCase))
                    return null;
                if (facts.EffectiveMatchText.Contains("Caught exception from", System.StringComparison.OrdinalIgnoreCase)
                    || facts.EffectiveMatchText.Contains("provided by", System.StringComparison.OrdinalIgnoreCase)
                    || facts.EffectiveMatchText.Contains("-- MOD", System.StringComparison.OrdinalIgnoreCase))
                    return null;
                var keys = facts.StackKeywords.Take(3).ToList();
                if (keys.Count == 0)
                    keys.Add("NullPointerException");
                return new CrashMatch
                {
                    RuleId = "USR005",
                    Cause = "UsrNpeUnbound",
                    Phase = CrashPhase.Primary,
                    Evidence = CrashEvidenceCollector.FindEvidenceLine(facts, "NullPointerException") ?? "NullPointerException",
                    Keywords = keys
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR006",
            Kind = "usr_nsme_unbound",
            Match = facts =>
            {
                var hit = facts.EffectiveMatchText.Contains("NoSuchMethodError", System.StringComparison.OrdinalIgnoreCase)
                          || facts.EffectiveMatchText.Contains("AbstractMethodError", System.StringComparison.OrdinalIgnoreCase);
                if (!hit)
                    return null;
                if (facts.SuspectedModsFromReport.Count > 0)
                    return null;
                var needle = facts.EffectiveMatchText.Contains("NoSuchMethodError", System.StringComparison.OrdinalIgnoreCase)
                    ? "NoSuchMethodError" : "AbstractMethodError";
                return new CrashMatch
                {
                    RuleId = "USR006",
                    Cause = "UsrNsmeUnbound",
                    Phase = CrashPhase.Primary,
                    Evidence = CrashEvidenceCollector.FindEvidenceLine(facts, needle) ?? needle,
                    Keywords = new[] { needle }.Concat(facts.StackKeywords.Take(3)).Distinct().Take(8).ToList()
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR007",
            Kind = "usr_loader_warn_multi",
            Match = facts =>
            {
                if (!(facts.EffectiveMatchText.Contains("Mod Resolution", System.StringComparison.OrdinalIgnoreCase)
                      || facts.EffectiveMatchText.Contains("Failed to load", System.StringComparison.OrdinalIgnoreCase)))
                    return null;
                var mods = facts.StackMappedMods.Take(5).ToList();
                if (mods.Count == 0)
                    return null;
                return new CrashMatch
                {
                    RuleId = "USR007",
                    Cause = "UsrLoaderWarnMulti",
                    Phase = CrashPhase.Primary,
                    Evidence = string.Join(", ", mods),
                    Mods = mods
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR008",
            Kind = "usr_fatal_logger_only",
            Match = facts =>
            {
                if (facts.HasCrashReport)
                    return null;
                if (!facts.EffectiveMatchText.Contains("/FATAL]", System.StringComparison.OrdinalIgnoreCase))
                    return null;
                var keys = facts.StackKeywords.Take(8).ToList();
                if (keys.Count == 0)
                    keys.Add("FATAL");
                return new CrashMatch
                {
                    RuleId = "USR008",
                    Cause = "UsrFatalLoggerOnly",
                    Phase = CrashPhase.Primary,
                    Evidence = CrashEvidenceCollector.FindEvidenceLine(facts, "/FATAL]") ?? "/FATAL]",
                    Keywords = keys
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR009",
            Kind = "usr_hserr_no_gpu_sig",
            Match = facts =>
            {
                if (!facts.HasHsErr && !facts.EffectiveMatchText.Contains("EXCEPTION_ACCESS_VIOLATION", System.StringComparison.OrdinalIgnoreCase)
                    && !facts.EffectiveMatchText.Contains("SIGSEGV", System.StringComparison.OrdinalIgnoreCase))
                    return null;
                if (facts.EffectiveMatchText.Contains("# C [ig", System.StringComparison.OrdinalIgnoreCase)
                    || facts.EffectiveMatchText.Contains("# C [atio", System.StringComparison.OrdinalIgnoreCase)
                    || facts.EffectiveMatchText.Contains("# C [nvoglv", System.StringComparison.OrdinalIgnoreCase))
                    return null;
                var keys = new List<string>();
                if (facts.EffectiveMatchText.Contains("EXCEPTION_ACCESS_VIOLATION", System.StringComparison.OrdinalIgnoreCase))
                    keys.Add("EXCEPTION_ACCESS_VIOLATION");
                if (facts.EffectiveMatchText.Contains("SIGSEGV", System.StringComparison.OrdinalIgnoreCase))
                    keys.Add("SIGSEGV");
                if (keys.Count == 0)
                    return null;
                return new CrashMatch
                {
                    RuleId = "USR009",
                    Cause = "UsrHsErrNoGpu",
                    Phase = CrashPhase.Primary,
                    Evidence = CrashEvidenceCollector.FindEvidenceLine(facts, keys[0]) ?? keys[0],
                    Keywords = keys
                };
            }
        },
        new UsrRuleDefinition
        {
            Id = "USR010",
            Kind = "usr_short_or_noisy",
            Match = facts =>
            {
                if (!facts.OutputVeryShort)
                    return null;
                var snippet = facts.EffectiveMatchText.Length <= 200 ? facts.EffectiveMatchText : facts.EffectiveMatchText[^200..];
                return new CrashMatch
                {
                    RuleId = "USR010",
                    Cause = "UsrShortOrNoisy",
                    Phase = CrashPhase.Primary,
                    Evidence = string.IsNullOrWhiteSpace(snippet) ? "(empty)" : snippet.Trim(),
                    Keywords = new[] { "short-output" }
                };
            }
        },
    ];
}
