#!/usr/bin/env python3
"""Emit only CrashRuleCatalog.g.cs from RULES in generate_crash_catalog.py (skip corrupted Loc)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "tools/crash-gen/generate_crash_catalog.py"
OUT = ROOT / "src/Ardel.Launcher/Services/CrashAnalysis/CrashRuleCatalog.g.cs"


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    text = SRC.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"RULES: list\[dict\] = (\[[\s\S]*?\n\])\n\n# English copy", text)
    if not m:
        raise SystemExit("Could not locate RULES list")
    # Evaluate RULES safely in an empty-ish namespace
    ns: dict = {}
    exec("RULES = " + m.group(1), {"True": True, "False": False}, ns)
    rules = ns["RULES"]

    parts = [
        "// <auto-generated> by tools/crash-gen/emit_rules_only.py",
        "namespace Ardel.Launcher.Services.CrashAnalysis;",
        "",
        "internal static class CrashRuleCatalog",
        "{",
        "    public static readonly CrashRuleDefinition[] Rules =",
        "    [",
    ]

    enabled = 0
    for r in rules:
        if r.get("disabled"):
            continue
        enabled += 1
        phase = "CrashPhase.Fatal" if r["phase"] == "F" else "CrashPhase.Primary"
        special = r.get("special")
        if special in ("prefer_crash_report",):
            needles = ", ".join(f'"{esc(n)}"' for n in r["needles"])
            match = f"facts => CrashRuleMatchers.ContainsPreferCrashReport(facts, {needles})"
        elif special in ("named_mod", "mixin_named"):
            needles = ", ".join(f'"{esc(n)}"' for n in r["needles"])
            match = f"facts => CrashRuleMatchers.NamedModEvidence(facts, {needles})"
        elif special == "jni_secondary":
            match = (
                'facts => facts.EffectiveMatchText.Contains("EXCEPTION_ACCESS_VIOLATION", '
                "System.StringComparison.OrdinalIgnoreCase) "
                '&& !facts.EffectiveMatchText.Contains("# C [ig", System.StringComparison.OrdinalIgnoreCase) '
                '&& !facts.EffectiveMatchText.Contains("# C [atio", System.StringComparison.OrdinalIgnoreCase) '
                '&& !facts.EffectiveMatchText.Contains("# C [nvoglv", System.StringComparison.OrdinalIgnoreCase) '
                '&& facts.EffectiveMatchText.Contains("# C [", System.StringComparison.OrdinalIgnoreCase) '
                '? CrashEvidenceCollector.FindEvidenceLine(facts, "EXCEPTION_ACCESS_VIOLATION") '
                ': null'
            )
        elif "all" in r:
            needles = ", ".join(f'"{esc(n)}"' for n in r["all"])
            match = f"facts => CrashRuleMatchers.ContainsAll(facts, {needles})"
        else:
            needles = ", ".join(f'"{esc(n)}"' for n in r["needles"])
            match = f"facts => CrashRuleMatchers.Contains(facts, {needles})"

        parts.append(
            "        new CrashRuleDefinition\n"
            "        {\n"
            f'            Id = "{r["id"]}",\n'
            f'            Cause = "{r["cause"]}",\n'
            f"            Phase = {phase},\n"
            "            Stop = true,\n"
            f"            Match = {match}\n"
            "        },"
        )

    parts += ["    ];", "}", ""]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} with {enabled} enabled rules (of {len(rules)} defined)")


if __name__ == "__main__":
    main()
