#!/usr/bin/env python3
"""Build day-observances.json from a curated international list only.

Rules:
- Fixed-date, internationally recognized observances (UN / WHO / UNESCO / widely known culture).
- Widely known national days / independence days (not US-only).
- No \"National X Day\" filler, no joke names, no invented days.
- Missing dates are omitted (Home shows date/weekday only).
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src/Ardel.Launcher/Assets/Data"
OUT_JSON = DATA / "day-observances.json"

# key MMDD -> (en, zh-Hans, zh-Hant, ja, fr, es, ko, de, pt, it, ru)
DAYS: dict[str, tuple[str, str, str, str, str, str, str, str, str, str, str]] = {
    # January
    "0101": ("New Year's Day", "元旦", "元旦", "元日", "Jour de l'An", "Año Nuevo", "새해 첫날", "Neujahr", "Ano Novo", "Capodanno", "Новый год"),
    "0104": ("World Braille Day", "世界盲文日", "世界盲文日", "世界点字の日", "Journée mondiale du braille", "Día Mundial del Braille", "세계 점자의 날", "Welt-Braille-Tag", "Dia Mundial do Braille", "Giornata mondiale del Braille", "Всемирный день Брайля"),
    "0106": ("Epiphany", "主显节", "主顯節", "公現祭", "Épiphanie", "Epifanía", "출현", "Epiphanie", "Epifania", "Epifania", "Крещение"),
    "0124": ("International Day of Education", "国际教育日", "國際教育日", "国際教育デー", "Journée internationale de l'éducation", "Día Internacional de la Educación", "국제 교육의 날", "Internationaler Tag der Bildung", "Dia Internacional da Educação", "Giornata internazionale dell'educazione", "Международный день образования"),
    # February
    "0202": ("World Wetlands Day", "世界湿地日", "世界濕地日", "世界湿地の日", "Journée mondiale des zones humides", "Día Mundial de los Humedales", "세계 습지의 날", "Weltfeuchtgebietstag", "Dia Mundial das Zonas Húmidas", "Giornata mondiale delle zone umide", "Всемирный день водно-болотных угодий"),
    "0204": ("World Cancer Day", "世界癌症日", "世界癌症日", "世界がんデー", "Journée mondiale contre le cancer", "Día Mundial contra el Cáncer", "세계 암의 날", "Weltkrebstag", "Dia Mundial do Câncer", "Giornata mondiale contro il cancro", "Всемирный день борьбы с раком"),
    "0210": ("World Pulses Day", "世界豆类日", "世界豆類日", "世界マメの日", "Journée mondiale des légumineuses", "Día Mundial de las Legumbres", "세계 펄스의 날", "Welttag der Hülsenfrüchte", "Dia Mundial das Leguminosas", "Giornata mondiale dei legumi", "Всемирный день зернобобовых"),
    "0211": ("International Day of Women and Girls in Science", "女童和妇女参与科学国际日", "女童和婦女參與科學國際日", "女性・女児の科学国際デー", "Journée internationale des femmes et des filles de science", "Día Internacional de las Mujeres y las Niñas en la Ciencia", "세계 여성과 소녀의 과학의 날", "Internationaler Tag der Frauen und Mädchen in der Wissenschaft", "Dia Internacional das Mulheres e Meninas na Ciência", "Giornata internazionale delle donne e delle ragazze nella scienza", "Международный день женщин и девочек в науке"),
    "0213": ("World Radio Day", "世界无线电日", "世界無線電日", "世界ラジオ・デー", "Journée mondiale de la radio", "Día Mundial de la Radio", "세계 라디오의 날", "Weltradiotag", "Dia Mundial da Rádio", "Giornata mondiale della radio", "Всемирный день радио"),
    "0214": ("Valentine's Day", "情人节", "情人節", "バレンタインデー", "Saint-Valentin", "Día de San Valentín", "발렌타인 데이", "Valentinstag", "Dia dos Namorados", "San Valentino", "День святого Валентина"),
    "0220": ("World Day of Social Justice", "世界社会公正日", "世界社會公正日", "世界社会正義の日", "Journée mondiale de la justice sociale", "Día Mundial de la Justicia Social", "세계 사회 정의의 날", "Welttag der sozialen Gerechtigkeit", "Dia Mundial da Justiça Social", "Giornata mondiale della giustizia sociale", "Всемирный день социальной справедливости"),
    "0221": ("International Mother Language Day", "国际母语日", "國際母語日", "国際母語デー", "Journée internationale de la langue maternelle", "Día Internacional de la Lengua Materna", "국제 모국어의 날", "Internationaler Tag der Muttersprache", "Dia Internacional da Língua Materna", "Giornata internazionale della lingua madre", "Международный день родного языка"),
    "0229": ("Leap Day", "闰日", "閏日", "うるう日", "Jour bissextile", "Día bisiesto", "윤일", "Schalttag", "Dia bissexto", "Giorno bisestile", "Високосный день"),
    # March
    "0301": ("Zero Discrimination Day", "零歧视日", "零歧視日", "ゼロ差別デー", "Journée zéro discrimination", "Día Cero Discriminación", "차별 제로의 날", "Tag der Nulldiskriminierung", "Dia da Discriminação Zero", "Giornata contro le discriminazioni zero", "День нулевой дискриминации"),
    "0303": ("World Wildlife Day", "世界野生动植物日", "世界野生動植物日", "世界野生生物の日", "Journée mondiale de la vie sauvage", "Día Mundial de la Vida Silvestre", "세계 야생동물의 날", "Welttag der Tierwelt", "Dia Mundial da Vida Selvagem", "Giornata mondiale della fauna selvatica", "Всемирный день дикой природы"),
    "0308": ("International Women's Day", "国际妇女节", "國際婦女節", "国際女性デー", "Journée internationale des femmes", "Día Internacional de la Mujer", "세계 여성의 날", "Internationaler Frauentag", "Dia Internacional da Mulher", "Giornata internazionale della donna", "Международный женский день"),
    "0314": ("Pi Day", "圆周率日", "圓周率日", "円周率の日", "Journée de Pi", "Día Pi", "파이 데이", "Pi-Tag", "Dia do Pi", "Giorno Pi", "День Пи"),
    "0320": ("International Day of Happiness", "国际幸福日", "國際幸福日", "国際幸福デー", "Journée internationale du bonheur", "Día Internacional de la Felicidad", "국제 행복의 날", "Internationaler Tag des Glücks", "Dia Internacional da Felicidade", "Giornata internazionale della felicità", "Международный день счастья"),
    "0321": ("International Day of Forests", "国际森林日", "國際森林日", "国際森林デー", "Journée internationale des forêts", "Día Internacional de los Bosques", "세계 숲의 날", "Internationaler Tag des Waldes", "Dia Internacional das Florestas", "Giornata internazionale delle foreste", "Международный день лесов"),
    "0322": ("World Water Day", "世界水日", "世界水日", "世界水の日", "Journée mondiale de l'eau", "Día Mundial del Agua", "세계 물의 날", "Weltwassertag", "Dia Mundial da Água", "Giornata mondiale dell'acqua", "Всемирный день воды"),
    "0323": ("World Meteorological Day", "世界气象日", "世界氣象日", "世界気象デー", "Journée météorologique mondiale", "Día Meteorológico Mundial", "세계 기상의 날", "Welttag der Meteorologie", "Dia Meteorológico Mundial", "Giornata mondiale della meteorologia", "Всемирный метеорологический день"),
    "0324": ("World Tuberculosis Day", "世界防治结核病日", "世界防治結核病日", "世界結核デー", "Journée mondiale de la tuberculose", "Día Mundial de la Tuberculosis", "세계 결핵의 날", "Welttuberkulosetag", "Dia Mundial da Tuberculose", "Giornata mondiale contro la tubercolosi", "Всемирный день борьбы с туберкулезом"),
    "0327": ("World Theatre Day", "世界戏剧日", "世界戲劇日", "世界演劇の日", "Journée mondiale du théâtre", "Día Mundial del Teatro", "세계 연극의 날", "Welttheatertag", "Dia Mundial do Teatro", "Giornata Mondiale del Teatro", "Всемирный день театра"),
    # April
    "0401": ("April Fools' Day", "愚人节", "愚人節", "エイプリルフール", "Poisson d'avril", "Día de los Inocentes", "만우절", "Aprilscherz", "Dia da Mentira", "Primo d'aprile", "Первоапрельский день дурака"),
    "0402": ("World Autism Awareness Day", "世界提高自闭症意识日", "世界提高自閉症意識日", "世界自閉症啓発デー", "Journée mondiale de sensibilisation à l'autisme", "Día Mundial de Concientización sobre el Autismo", "세계 자폐증 인식의 날", "Welt-Autismus-Bewusstseinstag", "Dia Mundial da Conscientização do Autismo", "Giornata Mondiale per la Consapevolezza sull'Autismo", "Всемирный день распространения информации об аутизме"),
    "0406": ("International Day of Sport for Development and Peace", "体育促进发展与和平国际日", "體育促進發展與和平國際日", "開発と平和のためのスポーツ国際デー", "Journée internationale du sport au service du développement et de la paix", "Día Internacional del Deporte para el Desarrollo y la Paz", "발전과 평화를 위한 세계 스포츠의 날", "Internationaler Tag des Sports für Entwicklung und Frieden", "Dia Internacional do Esporte para o Desenvolvimento e a Paz", "Giornata internazionale dello sport per lo sviluppo e la pace", "Международный день спорта на благо развития и мира"),
    "0407": ("World Health Day", "世界卫生日", "世界衛生日", "世界保健デー", "Journée mondiale de la santé", "Día Mundial de la Salud", "세계 보건의 날", "Weltgesundheitstag", "Dia Mundial da Saúde", "Giornata Mondiale della Salute", "Всемирный день здоровья"),
    "0412": ("International Day of Human Space Flight", "载人空间飞行国际日", "載人空間飛行國際日", "人間の宇宙飛行国際デー", "Journée internationale du vol spatial habité", "Día Internacional de los Vuelos Espaciales Tripulados", "국제 인간 우주 비행의 날", "Internationaler Tag der bemannten Raumfahrt", "Dia Internacional do Voo Espacial Humano", "Giornata internazionale del volo umano nello spazio", "Международный день полета человека в космос"),
    "0422": ("Earth Day", "世界地球日", "世界地球日", "アースデイ", "Jour de la Terre", "Día de la Tierra", "지구의 날", "Tag der Erde", "Dia da Terra", "Giornata della Terra", "День Земли"),
    "0423": ("World Book and Copyright Day", "世界图书和版权日", "世界圖書和版權日", "世界図書・著作権デー", "Journée mondiale du livre et du droit d'auteur", "Día Mundial del Libro y del Derecho de Autor", "세계 도서 및 저작권의 날", "Welttag des Buches und des Urheberrechts", "Dia Mundial do Livro e dos Direitos Autorais", "Giornata mondiale del libro e del diritto d'autore", "Всемирный день книги и авторского права"),
    "0425": ("World Malaria Day", "世界疟疾日", "世界瘧疾日", "世界マラリアデー", "Journée mondiale du paludisme", "Día Mundial de la Malaria", "세계 말라리아의 날", "Welt-Malaria-Tag", "Dia Mundial da Malária", "Giornata Mondiale contro la Malaria", "Всемирный день борьбы с малярией"),
    "0426": ("World Intellectual Property Day", "世界知识产权日", "世界知識產權日", "世界知的所有権の日", "Journée mondiale de la propriété intellectuelle", "Día Mundial de la Propiedad Intelectual", "세계 지적재산권의 날", "Welttag des geistigen Eigentums", "Dia Mundial da Propriedade Intelectual", "Giornata mondiale della proprietà intellettuale", "Всемирный день интеллектуальной собственности"),
    "0428": ("World Day for Safety and Health at Work", "世界安全生产与健康日", "世界安全生產與健康日", "労働安全衛生世界デー", "Journée mondiale de la sécurité et de la santé au travail", "Día Mundial de la Seguridad y Salud en el Trabajo", "직장에서의 안전과 건강을 위한 세계의 날", "Welttag für Sicherheit und Gesundheit am Arbeitsplatz", "Dia Mundial da Segurança e Saúde no Trabalho", "Giornata mondiale per la sicurezza e la salute sul lavoro", "Всемирный день безопасности и гигиены труда"),
    "0430": ("International Jazz Day", "国际爵士日", "國際爵士日", "国際ジャズ・デー", "Journée internationale du jazz", "Día Internacional del Jazz", "국제 재즈의 날", "Internationaler Jazztag", "Dia Internacional do Jazz", "Giornata internazionale del jazz", "Международный день джаза"),
    # May
    "0501": ("International Workers' Day", "国际劳动节", "國際勞動節", "メーデー", "Fête du Travail", "Día Internacional de los Trabajadores", "국제 노동자의 날", "Internationaler Arbeitertag", "Dia Internacional dos Trabalhadores", "Giornata internazionale dei lavoratori", "Международный день трудящихся"),
    "0504": ("Star Wars Day", "星球大战日", "星球大戰日", "スター・ウォーズの日", "Jour de Star Wars", "Día de la Guerra de las Galaxias", "스타워즈 데이", "Star Wars-Tag", "Dia de Guerra nas Estrelas", "Giornata di Guerre Stellari", "День Звездных войн"),
    "0508": ("World Red Cross and Red Crescent Day", "世界红十字与红新月日", "世界紅十字與紅新月日", "世界赤十字・赤新月デー", "Journée mondiale de la Croix-Rouge et du Croissant-Rouge", "Día Mundial de la Cruz Roja y de la Media Luna Roja", "세계 적십자 및 적신월의 날", "Weltrotkreuz- und Rothalbmondtag", "Dia Mundial da Cruz Vermelha e do Crescente Vermelho", "Giornata Mondiale della Croce Rossa e della Mezzaluna Rossa", "Всемирный день Красного Креста и Красного Полумесяца"),
    "0515": ("International Day of Families", "国际家庭日", "國際家庭日", "国際家族デー", "Journée internationale des familles", "Día Internacional de las Familias", "국제 가족의 날", "Internationaler Tag der Familie", "Dia Internacional das Famílias", "Giornata internazionale delle famiglie", "Международный день семьи"),
    "0517": ("World Telecommunication and Information Society Day", "世界电信和信息社会日", "世界電信和信息社會日", "世界電気通信・情報社会デー", "Journée mondiale des télécommunications et de la société de l'information", "Día Mundial de las Telecomunicaciones y la Sociedad de la Información", "세계 전기통신 및 정보사회의 날", "Welttag der Telekommunikation und Informationsgesellschaft", "Dia Mundial das Telecomunicações e da Sociedade da Informação", "Giornata mondiale delle telecomunicazioni e della società dell'informazione", "Всемирный день электросвязи и информационного общества"),
    "0518": ("International Museum Day", "国际博物馆日", "國際博物館日", "国際博物館の日", "Journée internationale des musées", "Día Internacional de los Museos", "국제 박물관의 날", "Internationaler Museumstag", "Dia Internacional dos Museus", "Giornata internazionale dei musei", "Международный день музеев"),
    "0521": ("World Day for Cultural Diversity", "世界文化多样性促进对话和发展日", "世界文化多樣性促進對話和發展日", "文化の多様性のための世界デー", "Journée mondiale de la diversité culturelle", "Día Mundial de la Diversidad Cultural", "세계 문화 다양성의 날", "Welttag für kulturelle Vielfalt", "Dia Mundial da Diversidade Cultural", "Giornata mondiale per la diversità culturale", "Всемирный день культурного разнообразия"),
    "0522": ("International Day for Biological Diversity", "国际生物多样性日", "國際生物多樣性日", "国際生物多様性の日", "Journée internationale de la diversité biologique", "Día Internacional de la Diversidad Biológica", "국제 생물 다양성의 날", "Internationaler Tag der biologischen Vielfalt", "Dia Internacional da Diversidade Biológica", "Giornata internazionale per la diversità biologica", "Международный день биологического разнообразия"),
    "0531": ("World No Tobacco Day", "世界无烟日", "世界無煙日", "世界禁煙デー", "Journée mondiale sans tabac", "Día Mundial Sin Tabaco", "세계 금연의 날", "Weltnichtrauchertag", "Dia Mundial Sem Tabaco", "Giornata mondiale senza tabacco", "Всемирный день без табака"),
    # June
    "0601": ("International Children's Day", "国际儿童节", "國際兒童節", "国際子どもの日", "Journée internationale des enfants", "Día Internacional del Niño", "국제 어린이날", "Internationaler Kindertag", "Dia Internacional da Criança", "Giornata internazionale dei bambini", "Международный день защиты детей"),
    "0602": ("Italy Republic Day", "意大利共和国日", "義大利共和國日", "イタリア共和国記念日", "Fête de la République italienne", "Día de la República de Italia", "이탈리아 공화국의 날", "Tag der italienischen Republik", "Dia da República da Itália", "Festa della Repubblica Italiana", "День Республики Италия"),
    "0605": ("World Environment Day", "世界环境日", "世界環境日", "世界環境デー", "Journée mondiale de l'environnement", "Día Mundial del Medio Ambiente", "세계 환경의 날", "Weltumwelttag", "Dia Mundial do Meio Ambiente", "Giornata mondiale dell'ambiente", "Всемирный день окружающей среды"),
    "0606": ("Sweden National Day", "瑞典国庆日", "瑞典國慶日", "スウェーデン国民の日", "Fête nationale suédoise", "Día Nacional de Suecia", "스웨덴 국경일", "Schwedischer Nationalfeiertag", "Dia Nacional da Suécia", "Festa nazionale della Svezia", "Национальный день Швеции"),
    "0607": ("World Food Safety Day", "世界食品安全日", "世界食品安全日", "世界食品安全デー", "Journée mondiale de la sécurité sanitaire des aliments", "Día Mundial de la Inocuidad de los Alimentos", "세계 식품 안전의 날", "Welttag der Lebensmittelsicherheit", "Dia Mundial da Segurança Alimentar", "Giornata mondiale della sicurezza alimentare", "Всемирный день безопасности пищевых продуктов"),
    "0608": ("World Oceans Day", "世界海洋日", "世界海洋日", "世界海洋デー", "Journée mondiale de l'océan", "Día Mundial de los Océanos", "세계 해양의 날", "Welttag der Ozeane", "Dia Mundial dos Oceanos", "Giornata mondiale degli oceani", "Всемирный день океанов"),
    "0614": ("World Blood Donor Day", "世界献血者日", "世界獻血者日", "世界献血者デー", "Journée mondiale des donneurs de sang", "Día Mundial del Donante de Sangre", "세계 헌혈자의 날", "Weltblutspendetag", "Dia Mundial do Doador de Sangue", "Giornata mondiale del donatore di sangue", "Всемирный день донора крови"),
    "0617": ("World Day to Combat Desertification and Drought", "防治荒漠化和干旱世界日", "防治荒漠化和乾旱世界日", "砂漠化および干ばつと闘う世界デー", "Journée mondiale de la lutte contre la désertification et la sécheresse", "Día Mundial de Lucha contra la Desertificación y la Sequía", "사막화 및 가뭄 퇴치를 위한 세계의 날", "Welttag zur Bekämpfung von Wüstenbildung und Dürre", "Dia Mundial de Combate à Desertificação e à Seca", "Giornata mondiale contro la desertificazione e la siccità", "Всемирный день борьбы с опустыниванием и засухой"),
    "0621": ("International Day of Yoga / World Music Day", "国际瑜伽日 / 世界音乐日", "國際瑜伽日 / 世界音樂日", "国際ヨガの日 / 音楽の日", "Journée internationale du yoga / Fête de la musique", "Día Internacional del Yoga / Día Mundial de la Música", "세계 요가의 날 / 세계 음악의 날", "Internationaler Tag des Yoga / Weltmusiktag", "Dia Internacional do Yoga / Dia Mundial da Música", "Giornata internazionale dello yoga/Giornata mondiale della musica", "Международный день йоги/Всемирный день музыки"),
    "0623": ("International Olympic Day", "国际奥林匹克日", "國際奧林匹克日", "オリンピックデー", "Journée olympique", "Día Olímpico Internacional", "국제 올림픽의 날", "Internationaler Olympischer Tag", "Dia Olímpico Internacional", "Giornata Olimpica Internazionale", "Международный олимпийский день"),
    "0626": ("International Day against Drug Abuse", "国际禁毒日", "國際禁毒日", "薬物乱用・不正取引反対国際デー", "Journée internationale contre l'abus et le trafic de drogues", "Día Internacional contra el Abuso de Drogas", "국제 약물 남용 방지의 날", "Internationaler Tag gegen Drogenmissbrauch", "Dia Internacional contra o Abuso de Drogas", "Giornata internazionale contro l'abuso di droga", "Международный день борьбы со злоупотреблением наркотиками"),
    # July
    "0701": ("Canada Day", "加拿大日", "加拿大日", "カナダデー", "Fête du Canada", "Día de Canadá", "캐나다 데이", "Kanada-Tag", "Dia do Canadá", "Giornata del Canada", "День Канады"),
    "0704": ("US Independence Day", "美国独立日", "美國獨立日", "アメリカ独立記念日", "Fête de l'Indépendance (États-Unis)", "Día de la Independencia de Estados Unidos", "미국 독립기념일", "US-Unabhängigkeitstag", "Dia da Independência dos EUA", "Giorno dell'Indipendenza degli Stati Uniti", "День независимости США"),
    "0711": ("World Population Day", "世界人口日", "世界人口日", "世界人口デー", "Journée mondiale de la population", "Día Mundial de la Población", "세계 인구의 날", "Weltbevölkerungstag", "Dia Mundial da População", "Giornata mondiale della popolazione", "Всемирный день народонаселения"),
    "0714": ("Bastille Day", "法国国庆日", "法國國慶日", "パリ祭 / フランス革命記念日", "Fête nationale française", "Día de la Bastilla", "바스티유 데이", "Bastille-Tag", "Dia da Bastilha", "Giorno della Bastiglia", "День взятия Бастилии"),
    "0720": ("International Moon Day", "国际月球日", "國際月球日", "国際月の日", "Journée internationale de la Lune", "Día Internacional de la Luna", "국제 달의 날", "Internationaler Mondtag", "Dia Internacional da Lua", "Giornata Internazionale della Luna", "Международный день Луны"),
    "0730": ("International Day of Friendship", "国际友谊日", "國際友誼日", "国際友情デー", "Journée internationale de l'amitié", "Día Internacional de la Amistad", "국제 우정의 날", "Internationaler Tag der Freundschaft", "Dia Internacional da Amizade", "Giornata internazionale dell'amicizia", "Международный день дружбы"),
    # August
    "0801": ("Swiss National Day", "瑞士国庆日", "瑞士國慶日", "スイス建国記念日", "Fête nationale suisse", "Día Nacional Suizo", "스위스 국경일", "Schweizer Nationalfeiertag", "Dia Nacional Suíço", "Festa nazionale svizzera", "Национальный день Швейцарии"),
    "0808": ("International Cat Day", "国际猫咪日", "國際貓咪日", "国際猫の日", "Journée internationale du chat", "Día Internacional del Gato", "국제 고양이의 날", "Internationaler Katzentag", "Dia Internacional do Gato", "Giornata internazionale del gatto", "Международный день кошек"),
    "0812": ("International Youth Day", "国际青年日", "國際青年日", "国際青年デー", "Journée internationale de la jeunesse", "Día Internacional de la Juventud", "국제 청소년의 날", "Internationaler Jugendtag", "Dia Internacional da Juventude", "Giornata Internazionale della Gioventù", "Международный день молодежи"),
    "0819": ("World Humanitarian Day", "世界人道主义日", "世界人道主義日", "世界人道デー", "Journée mondiale de l'aide humanitaire", "Día Mundial Humanitario", "세계 인도주의의 날", "Welttag der humanitären Hilfe", "Dia Mundial Humanitário", "Giornata umanitaria mondiale", "Всемирный день гуманитарной помощи"),
    "0826": ("International Dog Day", "国际狗狗日", "國際狗狗日", "国際犬の日", "Journée internationale du chien", "Día Internacional del Perro", "국제 개 날", "Internationaler Tag des Hundes", "Dia Internacional do Cão", "Giornata internazionale del cane", "Международный день собаки"),
    # September
    "0905": ("International Day of Charity", "国际慈善日", "國際慈善日", "国際チャリティーデー", "Journée internationale de la charité", "Día Internacional de la Caridad", "국제 자선의 날", "Internationaler Tag der Nächstenliebe", "Dia Internacional da Caridade", "Giornata Internazionale della Carità", "Международный день благотворительности"),
    "0907": ("Brazil Independence Day", "巴西独立日", "巴西獨立日", "ブラジル独立記念日", "Fête de l'indépendance du Brésil", "Día de la Independencia de Brasil", "브라질 독립기념일", "Brasiliens Unabhängigkeitstag", "Dia da Independência do Brasil", "Giorno dell'Indipendenza del Brasile", "День независимости Бразилии"),
    "0908": ("International Literacy Day", "国际扫盲日", "國際掃盲日", "国際識字デー", "Journée internationale de l'alphabétisation", "Día Internacional de la Alfabetización", "국제 문맹의 날", "Internationaler Tag der Alphabetisierung", "Dia Internacional da Alfabetização", "Giornata internazionale dell'alfabetizzazione", "Международный день грамотности"),
    "0916": ("Mexico Independence Day / International Day for the Preservation of the Ozone Layer", "墨西哥独立日 / 保护臭氧层国际日", "墨西哥獨立日 / 保護臭氧層國際日", "メキシコ独立記念日 / オゾン層保護のための国際デー", "Fête de l'indépendance du Mexique / Journée internationale de la protection de la couche d'ozone", "Día de la Independencia de México / Día Internacional de la Preservación de la Capa de Ozono", "멕시코 독립기념일 / 국제 오존층 보존의 날", "Mexiko-Unabhängigkeitstag / Internationaler Tag zur Erhaltung der Ozonschicht", "Dia da Independência do México / Dia Internacional para a Preservação da Camada de Ozônio", "Giorno dell'Indipendenza del Messico/Giornata internazionale per la preservazione dello strato di ozono", "День независимости Мексики / Международный день охраны озонового слоя"),
    "0921": ("International Day of Peace", "国际和平日", "國際和平日", "国際平和デー", "Journée internationale de la paix", "Día Internacional de la Paz", "국제 평화의 날", "Internationaler Tag des Friedens", "Dia Internacional da Paz", "Giornata internazionale della pace", "Международный день мира"),
    "0922": ("World Car-Free Day", "世界无车日", "世界無車日", "世界カーフリーデー", "Journée mondiale sans voiture", "Día Mundial Sin Coches", "세계 차 없는 날", "Weltautofreier Tag", "Dia Mundial Sem Carro", "Giornata mondiale senza auto", "Всемирный день без автомобилей"),
    "0927": ("World Tourism Day", "世界旅游日", "世界旅遊日", "世界観光の日", "Journée mondiale du tourisme", "Día Mundial del Turismo", "세계 관광의 날", "Welttourismustag", "Dia Mundial do Turismo", "Giornata Mondiale del Turismo", "Всемирный день туризма"),
    "0928": ("International Day for Universal Access to Information", "国际信息普及日", "國際信息普及日", "情報へのユニバーサル・アクセス国際デー", "Journée internationale de l'accès universel à l'information", "Día Internacional del Acceso Universal a la Información", "정보에 대한 보편적 접근을 위한 국제 날", "Internationaler Tag für den universellen Zugang zu Informationen", "Dia Internacional do Acesso Universal à Informação", "Giornata internazionale per l'accesso universale alle informazioni", "Международный день всеобщего доступа к информации"),
    "0929": ("International Day of Awareness of Food Loss and Waste", "国际粮食损失和浪费问题宣传日", "國際糧食損失和浪費問題宣傳日", "食品ロス削減国際デー", "Journée internationale de sensibilisation aux pertes et gaspillages alimentaires", "Día Internacional de Concientización sobre la Pérdida y el Desperdicio de Alimentos", "국제 식량 손실 및 폐기물 인식의 날", "Internationaler Tag des Bewusstseins für Lebensmittelverluste und -verschwendung", "Dia Internacional de Conscientização sobre Perda e Desperdício de Alimentos", "Giornata internazionale di sensibilizzazione sulle perdite e sugli sprechi alimentari", "Международный день борьбы с продовольственными потерями и порчей"),
    "0930": ("International Translation Day", "国际翻译日", "國際翻譯日", "国際翻訳デー", "Journée internationale de la traduction", "Día Internacional de la Traducción", "국제 번역의 날", "Internationaler Übersetzungstag", "Dia Internacional da Tradução", "Giornata internazionale della traduzione", "Международный день перевода"),
    # October
    "1001": ("China National Day", "中国国庆节", "中國國慶日", "中国の国慶節", "Fête nationale de la Chine", "Día Nacional de China", "중국 국경일", "China-Nationalfeiertag", "Dia Nacional da China", "Giornata nazionale cinese", "Национальный день Китая"),
    "1002": ("International Day of Non-Violence", "国际非暴力日", "國際非暴力日", "国際非暴力デー", "Journée internationale de la non-violence", "Día Internacional de la No Violencia", "국제 비폭력의 날", "Internationaler Tag der Gewaltlosigkeit", "Dia Internacional da Não-Violência", "Giornata internazionale della nonviolenza", "Международный день ненасилия"),
    "1003": ("German Unity Day", "德国统一日", "德國統一日", "ドイツ統一の日", "Jour de l'unité allemande", "Día de la Unidad Alemana", "독일 통일의 날", "Tag der Deutschen Einheit", "Dia da Unidade Alemã", "Giorno dell'Unità Tedesca", "День немецкого единства"),
    "1005": ("World Teachers' Day", "世界教师日", "世界教師日", "世界教員デー", "Journée mondiale des enseignants", "Día Mundial de los Docentes", "세계 교사의 날", "Weltlehrertag", "Dia Mundial dos Professores", "Giornata mondiale degli insegnanti", "Всемирный день учителя"),
    "1009": ("World Post Day", "世界邮政日", "世界郵政日", "世界郵便デー", "Journée mondiale de la poste", "Día Mundial del Correo", "세계 우편의 날", "Weltposttag", "Dia Mundial dos Correios", "Giornata mondiale della posta", "Всемирный день почты"),
    "1010": ("World Mental Health Day", "世界精神卫生日", "世界精神衛生日", "世界メンタルヘルスデー", "Journée mondiale de la santé mentale", "Día Mundial de la Salud Mental", "세계 정신 건강의 날", "Welttag der psychischen Gesundheit", "Dia Mundial da Saúde Mental", "Giornata mondiale della salute mentale", "Всемирный день психического здоровья"),
    "1011": ("International Day of the Girl Child", "国际女童日", "國際女童日", "国際ガールズ・デー", "Journée internationale de la fille", "Día Internacional de la Niña", "국제 여아의 날", "Internationaler Tag des Mädchenkindes", "Dia Internacional da Menina", "Giornata internazionale delle bambine", "Международный день девочек"),
    "1012": ("Spain National Day", "西班牙国庆日", "西班牙國慶日", "スペイン国民の日", "Fête nationale espagnole", "Día Nacional de España", "스페인 국경일", "Spanischer Nationalfeiertag", "Dia Nacional da Espanha", "Festa Nazionale della Spagna", "Национальный день Испании"),
    "1013": ("International Day for Disaster Risk Reduction", "国际减灾日", "國際減災日", "国際防災デー", "Journée internationale pour la réduction des risques de catastrophe", "Día Internacional para la Reducción del Riesgo de Desastres", "국제 재해 위험 감소의 날", "Internationaler Tag zur Reduzierung des Katastrophenrisikos", "Dia Internacional para a Redução do Risco de Desastres", "Giornata internazionale per la riduzione del rischio di catastrofi", "Международный день снижения риска стихийных бедствий"),
    "1016": ("World Food Day", "世界粮食日", "世界糧食日", "世界食料デー", "Journée mondiale de l'alimentation", "Día Mundial de la Alimentación", "세계 식량의 날", "Welternährungstag", "Dia Mundial da Alimentação", "Giornata mondiale dell'alimentazione", "Всемирный день еды"),
    "1017": ("International Day for the Eradication of Poverty", "消除贫困国际日", "消除貧困國際日", "貧困撲滅のための国際デー", "Journée internationale pour l'élimination de la pauvreté", "Día Internacional para la Erradicación de la Pobreza", "세계 빈곤 퇴치의 날", "Internationaler Tag zur Beseitigung der Armut", "Dia Internacional para a Erradicação da Pobreza", "Giornata internazionale per l'eliminazione della povertà", "Международный день борьбы за ликвидацию бедности"),
    "1024": ("United Nations Day", "联合国日", "聯合國日", "国連デー", "Journée des Nations Unies", "Día de las Naciones Unidas", "유엔의 날", "Tag der Vereinten Nationen", "Dia das Nações Unidas", "Giornata delle Nazioni Unite", "День Организации Объединенных Наций"),
    "1031": ("World Cities Day / Halloween", "世界城市日 / 万圣节", "世界城市日 / 萬聖節", "世界都市デー / ハロウィン", "Journée mondiale des villes / Halloween", "Día Mundial de las Ciudades / Halloween", "세계 도시의 날 / 할로윈", "Weltstädtetag / Halloween", "Dia Mundial das Cidades / Halloween", "Giornata Mondiale delle Città/Halloween", "Всемирный день городов / Хэллоуин"),
    # November
    "1101": ("World Vegan Day", "世界纯素日", "世界純素日", "世界ヴィーガンデー", "Journée mondiale du véganisme", "Día Mundial del Vegano", "세계 비건의 날", "Welt-Vegan-Tag", "Dia Mundial Vegano", "Giornata mondiale vegana", "Всемирный день вегана"),
    "1110": ("World Science Day for Peace and Development", "世界科学日", "世界科學日", "平和と開発のための世界科学デー", "Journée mondiale de la science au service de la paix et du développement", "Día Mundial de la Ciencia para la Paz y el Desarrollo", "평화와 발전을 위한 세계 과학의 날", "Weltwissenschaftstag für Frieden und Entwicklung", "Dia Mundial da Ciência para a Paz e o Desenvolvimento", "Giornata mondiale della scienza per la pace e lo sviluppo", "Всемирный день науки за мир и развитие"),
    "1111": ("Poland Independence Day / Singles' Day", "波兰独立日 / 双十一", "波蘭獨立日 / 雙十一", "ポーランド独立記念日 / 独身の日", "Fête de l'indépendance de la Pologne / Journée des célibataires", "Día de la Independencia de Polonia / Día de los Solteros", "폴란드 독립기념일 / 광군절", "Unabhängigkeitstag Polens / Tag der Singles", "Dia da Independência da Polónia / Dia dos Solteiros", "Giorno dell'Indipendenza della Polonia / Giorno dei Single", "День независимости Польши / День холостяков"),
    "1114": ("World Diabetes Day", "世界糖尿病日", "世界糖尿病日", "世界糖尿病デー", "Journée mondiale du diabète", "Día Mundial de la Diabetes", "세계 당뇨병의 날", "Weltdiabetestag", "Dia Mundial do Diabetes", "Giornata mondiale del diabete", "Всемирный день борьбы с диабетом"),
    "1116": ("International Day for Tolerance", "国际宽容日", "國際寬容日", "国際寛容デー", "Journée internationale de la tolérance", "Día Internacional de la Tolerancia", "국제 관용의 날", "Internationaler Tag der Toleranz", "Dia Internacional da Tolerância", "Giornata internazionale per la tolleranza", "Международный день толерантности"),
    "1119": ("World Toilet Day", "世界厕所日", "世界廁所日", "世界トイレの日", "Journée mondiale des toilettes", "Día Mundial del Retrete", "세계 화장실의 날", "Welttoilettentag", "Dia Mundial do Banheiro", "Giornata mondiale della toilette", "Всемирный день туалета"),
    "1120": ("World Children's Day", "世界儿童日", "世界兒童日", "世界子どもの日", "Journée mondiale de l'enfance", "Día Mundial del Niño", "세계 어린이날", "Weltkindertag", "Dia Mundial da Criança", "Giornata mondiale dei bambini", "Всемирный день детей"),
    "1121": ("World Television Day", "世界电视日", "世界電視日", "世界テレビ・デー", "Journée mondiale de la télévision", "Día Mundial de la Televisión", "세계 텔레비전의 날", "Weltfernsehtag", "Dia Mundial da Televisão", "Giornata mondiale della televisione", "Всемирный день телевидения"),
    # December
    "1203": ("International Day of Persons with Disabilities", "国际残疾人日", "國際殘疾人日", "国際障害者デー", "Journée internationale des personnes handicapées", "Día Internacional de las Personas con Discapacidad", "세계 장애인의 날", "Internationaler Tag der Menschen mit Behinderungen", "Dia Internacional das Pessoas com Deficiência", "Giornata internazionale delle persone con disabilità", "Международный день людей с ограниченными возможностями"),
    "1205": ("International Volunteer Day", "国际志愿人员日", "國際志願人員日", "国際ボランティアデー", "Journée internationale des volontaires", "Día Internacional del Voluntariado", "국제 자원봉사자의 날", "Internationaler Tag der Freiwilligen", "Dia Internacional do Voluntário", "Giornata Internazionale del Volontariato", "Международный день волонтеров"),
    "1206": ("Finland Independence Day", "芬兰独立日", "芬蘭獨立日", "フィンランド独立記念日", "Fête de l'indépendance de la Finlande", "Día de la Independencia de Finlandia", "핀란드 독립기념일", "Unabhängigkeitstag Finnlands", "Dia da Independência da Finlândia", "Giorno dell'indipendenza della Finlandia", "День независимости Финляндии"),
    "1207": ("International Civil Aviation Day", "国际民航日", "國際民航日", "国際民間航空デー", "Journée de l'aviation civile internationale", "Día Internacional de la Aviación Civil", "국제 민간 항공의 날", "Internationaler Tag der Zivilluftfahrt", "Dia Internacional da Aviação Civil", "Giornata internazionale dell'aviazione civile", "Международный день гражданской авиации"),
    "1211": ("International Mountain Day", "国际山岳日", "國際山岳日", "国際山岳デー", "Journée internationale de la montagne", "Día Internacional de la Montaña", "국제 산의 날", "Internationaler Bergtag", "Dia Internacional da Montanha", "Giornata Internazionale della Montagna", "Международный день гор"),
    "1220": ("International Human Solidarity Day", "国际人类团结日", "國際人類團結日", "国際人間連帯デー", "Journée internationale de la solidarité humaine", "Día Internacional de la Solidaridad Humana", "국제인류연대의 날", "Internationaler Tag der menschlichen Solidarität", "Dia Internacional da Solidariedade Humana", "Giornata internazionale della solidarietà umana", "Международный день человеческой солидарности"),
    "1224": ("Christmas Eve", "平安夜", "平安夜", "クリスマス・イブ", "Réveillon de Noël", "Nochebuena", "크리스마스 이브", "Heiligabend", "Noite de Natal", "Vigilia di Natale", "сочельник"),
    "1225": ("Christmas", "圣诞节", "聖誕節", "クリスマス", "Noël", "Navidad", "크리스마스", "Weihnachten", "Natal", "Natale", "Рождество"),
    "1231": ("New Year's Eve", "除夕 / 跨年夜", "除夕 / 跨年夜", "大みそか", "Saint-Sylvestre", "Nochevieja", "새해 전날", "Silvester", "Véspera de Ano Novo", "Vigilia di Capodanno", "Канун Нового года"),
}


def main() -> None:
    # Runtime compact format
    runtime = {k: list(v) for k, v in sorted(DAYS.items())}
    OUT_JSON.write_text(
        json.dumps(runtime, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
        newline="\n",
    )

    print(f"wrote {len(DAYS)} observances -> {OUT_JSON.name}")


if __name__ == "__main__":
    main()
